### ISSUE TITLE
deleteAllowingNoWhereFrom question

### ISSUE THREAD

**Issue by mkupriichuk** [juanluispaz/ts-sql-query#103]
Hello

I have a question about ```deleteAllowingNoWhereFrom```

It is just used for throw error if user try to delete some without ```where``` and final query still like this:

```
DELETE FROM mytable
```

Or it also toogle ```SQL_SAFE_UPDATE```?:

```
SET SQL_SAFE_UPDATES = 0;
DELETE FROM mytable
SET SQL_SAFE_UPDATES = 1;
```

Thanks

**Comment by juanluispaz** [comment]
Hi

ts-sql-query offers two different methods to create a delete query, `deleteFrom` and `deleteAllowingNoWhereFrom`. The method `deleteFrom`will force you to provide a `where` in your query, and if you ended without a `where` (maybe you are creating a dynamic query) the library will throw an error without execute any SQL.  The `deleteAllowingNoWhereFrom` allows you to remove that protection, in that case a delete query without a `where` can be executed.

The presence of a where clause is validated during the SQL generation, the database is not get involved; then the `SQL_SAFE_UPDATE` flag (MySQL, MariaDB) is not used or generated in any case.

No matter the method you use, the SQL will be the same when there is a where clause.

**From the documentation:**

> ts-sql-query will reject the execution of the delete sentence if, for some reason ended without a where. If you want to allow a delete without where, you must call connection.deleteAllowingNoWhereFrom instead of connection.deleteFrom when you start writing the sentence.

If you need to set the flag in your queries, I can offer you to add an additional [delete query customization](https://ts-sql-query.readthedocs.io/en/stable/queries/sql-fragments/#customizing-a-delete); right now there is an `afterQuery` and I can add a `beforeQuery`.

Let me know your thoughts on this.

**Comment by mkupriichuk** [comment]
Yes, ``beforeQuery`` would be nice

Thanks

**Comment by juanluispaz** [comment]
Hi,

Yes, it is possible, but it is not documented.


You can do things like:

```ts
await connection.queryRunner.executeDatabaseSchemaModification(`
            create table company (
                id int auto_increment primary key,
                name varchar(100) not null,
                parent_id int null references company(id)
            )
        `)
```

That is what I use in the examples.

Query runners are the low-level abstraction to interact with databases; all the queries in ts-sql-query are executed using it. Some databases or connectors are more complex than others ones; because of it, you will see something more complex than an execute raw query.

Inside the query runner, there are several functions that describe the intention of your query and what to get as output; see the list [here](https://github.com/juanluispaz/ts-sql-query/blob/v1.53.0/src/queryRunners/QueryRunner.ts). In the list, there is no one with a proper name for your case, but you can use `executeDatabaseSchemaModification` or `executeProcedure` in your case (MySql connector):

```ts
await connection.transaction(async () => {
     await connection.queryRunner. executeProcedure('SET SQL_SAFE_UPDATES = 0;');
      // deleteQuery
     await connection.queryRunner. executeProcedure('SET SQL_SAFE_UPDATES = 1;');
     // insertQuery
});
```

The function `execute` in the query runner brings you the most flexibility because, in that case, you will receive the connection object of your connector; then, you can do whatever you want with it.

Let me know your feedback.

**Comment by mkupriichuk** [comment]
Thanks, ```executeProcedure``` works fine.

Are you planning to add ```beforeQuery``` anyway?

**Comment by juanluispaz** [comment]
Released ts-sql-query 1.54.0 with some changes for you:

- I added `executeConnectionConfiguration` to the query runners; in that way, you have a function that expresses better what you are trying to do instead of `executeProcedure` which can have a confusing naming in this case.
- I added `beforeQuery` as a possibility to customise your queries.

Let me know your feedback.

**Comment by mkupriichuk** [comment]
Hi, thanks for update
I tested ```beforeQuery``` . With ```afterQuery``` combination my code looks like this:

```
    await connection.transaction(async () => {
      await connection
        .deleteAllowingNoWhereFrom(similarCategoryTable)
        .customizeQuery({
          beforeQuery: connection.rawFragment`SET SQL_SAFE_UPDATES = 0;`,
          afterQuery: connection.rawFragment`;SET SQL_SAFE_UPDATES = 1`
        })
        .executeDelete();
      await connection.insertInto(similarCategoryTable).values(values).executeInsert();
    });
```

And its works fine.

I also tested ```executeConnectionConfiguration```:

```
    await connection.transaction(async () => {
      await connection.queryRunner.executeConnectionConfiguration(`SET SQL_SAFE_UPDATES = 0;`);
      await connection.deleteAllowingNoWhereFrom(similarCategoryTable).executeDelete();
      await connection.queryRunner.executeConnectionConfiguration(`SET SQL_SAFE_UPDATES = 1;`);
      await connection.insertInto(similarCategoryTable).values(values).executeInsert();
    });
```

But in this case a got a error:

```
You are trying to configure a connection when you didn't request a dedicated connection. Begin a transaction to get a dedicated connection
```

**Comment by juanluispaz** [comment]
Oh, I will review it, it should throw the error when you are not in a transaction

**Comment by juanluispaz** [comment]
Release ts-sql-query 1.55.0 with changes regarding the last error; please, test it again and let me know your feedback.

**Comment by mkupriichuk** [comment]
all works fine, thanks
