### ISSUE TITLE
Optional column contextually mandatory

### ISSUE THREAD

**Issue by DGCarramona** [juanluispaz/ts-sql-query#118]
Hello,
Just beginning using this awesome library.
I'm using a postgresql DBMS.
I have a table (let's call it student) which has an optional column (let's call it age).
I'm trying to fetch a row matching type `{age: int}` but as the column is optional, it seems to be able only to retrieve `{age: int|undefined}`. In the query, I'm already restraining on only rows containing a value for age (using `where(student.age.isNotNull())` so can I instruct typescript this column is necessarily an int ?

**Comment by juanluispaz** [comment]
Hi,

Right now, detect automatically the column's type is not null because your where condition is not possible.

Type narrowing will be a dream, but I haven't yet found a manageable way to implement it without killing the TypeScript compiler. Having said that, you can still archive the output you want if you provide a little help. Using a [SQL fragment](https://ts-sql-query.readthedocs.io/en/stable/queries/sql-fragments/#select-with-custom-reusable-sql-fragment), you can circumvent the limitation. Example:

You define in your connection a fragment that changes the optionality rule:

```ts
class DBConnection extends PostgreSqlConnection<'DBConnection'> { 
    asNotNullInt = this.buildFragmentWithArgs(
        this.arg('int', 'optional')
    ).as((value) => {
        return this.fragmentWithType('int', 'required').sql`${value}`
    })
}
```

And then you use it in your query as:

```ts
    let studentWithAge = await connection.selectFrom(tStudent)
        .where(student.age.isNotNull())
        .select({
            id: tStudent.id,
            firstName: tStudent.firstName,
            lastName: tStudent.lastName,
            age: connection.asNotNullInt(tStudent.age)
        })
        .executeSelectOne()
```

I'm looking for a way to make this more general, but I'm still exploring some approaches.

Let me know if this solves your issue.

**Comment by lorefnon** [comment]
We often use the [SetRequired](https://github.com/sindresorhus/type-fest/blob/main/source/set-required.d.ts) type in type-fest which can be quite convenient for use cases like this, esp. if you mostly select all columns. 

    export type StudentSRow = SelectedRow<StudentTable>;
    export const tStudentCols = extractColumnsFrom(tStudent);

    let studentWithAge = (
        await connection.selectFrom(tStudent)
          .where(student.age.isNotNull())
          .select(tStudentCols)
          .executeSelectOne()
    ) as SetRequired<StudentSRow, "age">

**Comment by DGCarramona** [comment]
Thanks for you answer @juanluispaz . I just tried your solution and it convinced me 👍
