### ISSUE TITLE
[Question] Advanced time types

### ISSUE THREAD

**Issue by DGCarramona** [juanluispaz/ts-sql-query#121]
Hello,
Did you planned something for more advanced time types like interval in PostgreSQL ?

**Comment by juanluispaz** [comment]
Hi!

I'm trying to avoid including by default types that don't have direct representation in JavaScript from the different supported databases. Still, you can use your custom types as [column type](https://ts-sql-query.readthedocs.io/en/stable/column-types/) to provide your own type according to your project needs. There are several 'custom' types available.

Defining your own types allows you to use types not included in TypeScript, maybe because they don't have direct representation in TypeScript, maybe because they don't have direct representation in the database, or maybe because you want to transform the type because there is a mismatch between database representation, connector representation and typescript representation.

If you need to call specific functions on those specific types, you can create [Sql fragments](https://ts-sql-query.readthedocs.io/en/stable/queries/sql-fragments/); most of the time, this approach is enough to handle the additional types.

See the RgbColor example in [globally type adapter](https://ts-sql-query.readthedocs.io/en/stable/column-types/#globally-type-adapter); this will allow you to represent the interval in the most convenient way for your project.

I really want to see JavaScript Temporal API released, which will include several new types to manage better time-related types, like intervals that will represented with a temporal duration object.

Let me know if that works for you.

**Comment by DGCarramona** [comment]
Thank you for the answer. Indeed that seems to work, just a bit more of customization on my side.
