### ISSUE TITLE
Error "Forbidden concurrent usage of the query runner was detected when it tried to get a database connection from the pool"

### ISSUE THREAD

**Issue by DGCarramona** [juanluispaz/ts-sql-query#123]
Hello,
I've just got error "Forbidden concurrent usage of the query runner was detected when it tried to get a database connection from the pool". What does exactly mean that error ? Does it mean I cannot execute multiple queries in parallel ? What if I receive multiple http calls for instance ? Is there a specific param to set to allow it ?
I'm using PgPoolQueryRunner and instantiating connexion as `const connexion = new DBConnection(new PgPoolQueryRunner(pool));` (DBConnection extends PostgreSqlConnection)

**Comment by juanluispaz** [comment]
Hi,

DBConnection represents a [dedicated connection](https://ts-sql-query.readthedocs.io/en/stable/connection-tables-views/#instantiating-the-connection-with-the-database-connection) even when they are coming from the pool. Please create a new DBConnection instance for each HTTP request you receive.

Please let me know if that works for you.

**Comment by DGCarramona** [comment]
Thank you for the answer, sorry I didn't realized it while reading the documentation.

**Comment by juanluispaz** [comment]
Don't worry 😄 

I'm thinking to put a noter in every query runner that receives a connection pool.

If you have any idea how to improve it, please share with me.

**Comment by DGCarramona** [comment]
I'm still seeing something strange. At the start of the main function I create the query runner with the pool, then I create a dedicated connection just before executing a new query but I still have the aforementioned error.

**Comment by juanluispaz** [comment]
Ensure you  have it per request base and as well you are not running query in parallel. It is easy to forget an `await` and start doing queries in parallel agains your database.

**Comment by DGCarramona** [comment]
I'm creating the connection right before executing the query so even for a same http query, there will be multiple connections (one for each query).
I'm sure there is no missing `await`.
If I create each time a connection AND a query runner it works, issue arises only when using same query runner even for multiple connections.

**Comment by juanluispaz** [comment]
Can you tell me What QueryRunner are you using?

We usually create the DBConnection (with all its arguments, that means all query runner path) when the request is received in the server and we put in the context.

Example:
```ts
function createDBConnectionInstance() {
    // NOTE: PGPool can be global, but, DBConnection, neither any query runner can be global
    return new DBConnection(new ConsoleLogQueryRunner(new PgPoolQueryRunner(pool)))
}
```

**Comment by DGCarramona** [comment]
I'm still struggling to fully understand the purpose of the query runner and its difference with the connection but indeed this helps.

**Comment by juanluispaz** [comment]
There are several reasons:

1. It allows you to put a chain of interceptors for the query executions; in the previous example, I put `ConsoleLogQueryRunner`; in our development, we have a more complex thing that allows us to track and monitor what is happening with our queries, collect information to detect when the system is not behaving properly. See [InterceptorQueryRunner](https://ts-sql-query.readthedocs.io/en/stable/query-runners/general-purpose-query-runners/#interceptorqueryrunner). In our projects, we have several interceptors. See [Query execution metadata](https://ts-sql-query.readthedocs.io/en/stable/advanced-usage/#query-execution-metadata) for some ideas.

2. It allows you to create tests [mocking the database](https://ts-sql-query.readthedocs.io/en/stable/connection-tables-views/#instantiating-the-connection-with-a-mock-database-connection) without changing your code; in that case, a real `PgPool` or `PgConnection` will not be used. We prefer tests that run against a real database, but this can be useful if you do more unit testing instead of integration testing; we do it occasionally, and I know several ts-sql-query users are using it heavily.

3. It allows you to have multiple implementations depending on the connector you want to use; ts-sql-query 1 allows you to connect to PostgresSql using 9 different ways (`Pg` represents only two of them). Yes it can be archived using 9 different kind of PostgreSqlConnection, but you will understand that will be messy.
