### ISSUE TITLE
Using constant values in select()

### ISSUE THREAD

**Issue by threema-danilo** [juanluispaz/ts-sql-query#15]
If I do something like this...

```typescript
this._db
  .selectFrom(tContact)
  .select({
      uid: tContact.uid,
      name: tContact.name,
  })
  .where(tContact.uid.equals(123))
  .executeSelectNoneOrOne();
```

...this corresponds to the following query.

```sql
SELECT tContact.uid, tContact.name
FROM contacts as tContact
WHERE tContact.uid = 123
```

I need to add a constant value to every row returned by this query. In SQL, this would be:

```sql
SELECT tContact.uid, tContact.name, 'contact' as type
FROM contacts as tContact
WHERE tContact.uid = 123
```

However, the following `select()` call does not work:

```typescript
this._db
  .selectFrom(tContact)
  .select({
      uid: tContact.uid,
      name: tContact.name,
      type: 'contact',
  })
  .where(tContact.uid.equals(123))
  .executeSelectNoneOrOne();
```

Is there a way of using a constant value as a value source in a select query?

**Comment by juanluispaz** [comment]
Hi,

the connection object allows you to create const values using the methods:

- `connection.const`
- `connection.optionalConst`

There is an example in the [documentation](https://ts-sql-query.readthedocs.io/en/stable/queries/select/#select-with-a-compound-operator-union-intersect-except) that looks like what are you trying to do. I put the code here for you:

```ts
const allDataWithName = connection.selectFrom(tCustomer)
    .select({
        id: tCustomer.id,
        name: tCustomer.firstName.concat(' ').concat(tCustomer.lastName),
        type: connection.const<'customer' | 'company'>('customer', 'enum', 'customerOrCompany')
    }).unionAll(
        connection.selectFrom(tCompany)
        .select({
            id: tCompany.id,
            name: tCompany.name,
            type: connection.const<'customer' | 'company'>('company', 'enum', 'customerOrCompany')
        })
    ).executeSelectMany();
```

The generated query is:
```sql
select id as id, first_name || $1 || last_name as name, $2 as type 
from customer 

union all 

select id as id, name as name, $3 as type 
from company
```

The params: `[ ' ', 'customer', 'company' ]`

And the result type:
```ts
const allDataWithName: Promise<{
    id: number;
    name: string;
    type: "customer" | "company";
}[]>
```

You can use use any type available; I used in this example the enum `customerOrCompany` because what I was looking for was the column `type` type be `"customer" | "company"`. You can use `connection.const('contact', 'string')` if you wish.

**Comment by threema-danilo** [comment]
Thank you for your quick help, that seems to work!
