### ISSUE TITLE
Comparable custom types

### ISSUE THREAD

**Issue by threema-danilo** [juanluispaz/ts-sql-query#20]
I have a date column that looks like this:

    public processedAt = this.column<Date>('processedAt', 'custom', CUSTOM_TYPES.DATETIME);

This type is converted to/from a `Date` in the connection class.

The issue is that this column is not comparable, so I cannot use methods like `.larger` on it, even though the database storage format is an integer.

Is there a way to mark a custom type as `ComparableValueSource`?

**Comment by juanluispaz** [comment]
Hi,

The `column` function have different overload including:

```ts
column<T>(name: string, type: 'custom', typeName: string, adapter?: TypeAdapter): EqualableValueSource
column<T>(name: string, type: 'customComparable', typeName: string, adapter?: TypeAdapter): ComparableValueSource
```

The one you are looking for is `customComparable` instead of `custom`.

Any case, I want to have date working out of the box. According [sqlite documentation](https://www.sqlite.org/datatype3.html#affinity_name_examples) columns type called `DATE` and `DATETIME` (and will be the same with `TIME`) are treated as `NUMERIC` as you expressed.

The current implementation do the following:
- `LocalDate` are handled as javascript date object and delegated to the database connector
- `LocalDateTime` are handled as javascript date object and delegated to the database connector
- `LocalTime` are returned as javascript date to you but handled as string with format `HH:MM(:SS(.SSS))`

Now I realise delegating date object to the database connector is wrong in the sqlite case, it is not full working. I'm not sure which one must be the default value.

The default behaviour per connector is:
- `SqliteQueryRunner`, `Sqlite3QueryRunner`, `AnyDBQueryRunner`, `LoopBackQueryRunner`: the connector here transform to number using Date.getTime(), but it is not transformed back
- `BetterSqlite3QueryRunner`: fails
- `PrismaQueryRunner`: he connector here transform to string. It works back

I think the correct behaviour will be deal this types as numeric in all cases, using Date.getTime() function, but add a configuration flag that allows to use numeric representation instead of string representation as:
- `LocalDate` as `YYYY-MM-DD`
- `LocalDateTime` as `YYYY-MM-DDTHH:MM(:SS(.SSS))` (the one supported by javascript Date.parse)
- `LocalTime` as `HH:MM(:SS(.SSS))`

Please can you share with me the rules that you use to transform:
- LocalDate to sqlite's numeric
- LocalDateTime to sqlite's numeric
- LocalTime to sqlite's numeric
- Sqlite's numeric to LocalDate
- Sqlite's numeric to LocalDateTime
- Sqlite's numeric to LocalTime

I want to include it by default in the library (you can overwrite it if you need).

What are your thoughts on this?

**Comment by juanluispaz** [comment]
I added support to Date and Time management in sqlite using different strategies to represent the value (sqlite doesn't have dedicate types to represent dates and time). 

The implemented strategies are aligned with the date time support in sqlite allowing to store the information as text (in the local timezone or UTC), as integer (in unix time seconds) or as a real value (in Julian days).

You can see the documentation at https://ts-sql-query.readthedocs.io/en/latest/supported-databases/#sqlite 

This change is not published yet in npm.

I will appreciate your feedback on this.

**Comment by juanluispaz** [comment]
Changes included in ts-sql-query 1.15.0 now published

**Comment by juanluispaz** [comment]
Changes included in ts-sql-query 1.16.0 now published (skip the previous version due a small bug)

**Comment by threema-danilo** [comment]
Thanks for your work on this, and sorry for the late reply, I was in vacations last week.

> The one you are looking for is `customComparable` instead of `custom`.

Ah, I overlooked that (I was trying to get it to work by altering the type parameter, not the method).  You seem to have thought of everything! That should work for me.

> Any case, I want to have date working out of the box. According [sqlite documentation](https://www.sqlite.org/datatype3.html#affinity_name_examples) columns type called `DATE` and `DATETIME` (and will be the same with `TIME`) are treated as `NUMERIC` as you expressed.

To avoid ambiguity, I don't use DATE and DATETIME columns in SQLite, but instead store unix timestamps (in milliseconds) and use INTEGER columns. This also deals nicely with timezones, since timestamps are always relative to UTC-0.

The tricky thing is the poor timezone support in JavaScript, but since we always use timestamp based dates in our data model, this works out (in JS a `Date` is a representation of a UTC-0 timestamp, only the conversion to a text representation is dependent on the computer's local timezone).

> I think the correct behaviour will be deal this types as numeric in all cases, using Date.getTime() function, but add a configuration flag that allows to use numeric representation instead of string representation as:
> 
> * `LocalDate` as `YYYY-MM-DD`
> * `LocalDateTime` as `YYYY-MM-DDTHH:MM(:SS(.SSS))` (the one supported by javascript Date.parse)
> * `LocalTime` as `HH:MM(:SS(.SSS))`

Some databases like PostgreSQL have proper types that differentiate between naive timestamps (`timestamp` or `timestamp without time zone`) and timezone-aware timestamps (`timestamp with time zone`). However, the database layer doesn't really know whether a `Date` object should be treated as naive/local date, or whether it references UTC, so it's hard to do a one-size-fits-all solution. You seem to have considered that in your design.

> Please can you share with me the rules that you use to transform:
> 
> * LocalDate to sqlite's numeric
> * LocalDateTime to sqlite's numeric
> * LocalTime to sqlite's numeric
> * Sqlite's numeric to LocalDate
> * Sqlite's numeric to LocalDateTime
> * Sqlite's numeric to LocalTime

Right now I only use columns which use the `INTEGER` type in the SQLite database to store timestamp milliseconds. The conversion from database looks like this:

```typescript
if (typeof value === 'number') {
    return new Date(value);
} else if (typeof value === 'bigint') {
    // Note: Assuming here that the precision of a u53 is sufficient
    return new Date(Number(value));
}
```

Conversion to database looks like this:

```typescript
if (value instanceof Date) {
    return value.valueOf();
}
```

Regarding your implementation (as documented [here](https://ts-sql-query.readthedocs.io/en/latest/supported-databases/#sqlite)), I think this is a good general-purpose approach. I think I'd miss some kind of strict mode, where unexpected values (e.g. numeric if a string-based approach is chosen) results in an error, and not a re-interpretation. (I know that SQLite is very dynamic with its type support, and I hate it 😄)

For numeric storage, you provide `Unix time seconds as integer`. Maybe there should also be `Unix time milliseconds as integer` and maybe `Unix time microseconds as integer`? (In the latter case, make sure to use bigint in JS, since 2^53 microseconds since 1970 is 2255-6-6, which is not _that_ far into the future).

Another approach would be to use fractional seconds, e.g. `Unix time seconds as real` (re-using the SQLite type terminology).

**Comment by juanluispaz** [comment]
Hi,

I implemented all the options supported by (sqlite date and time functions)[https://www.sqlite.org/lang_datefunc.html] and unix time in milliseconds is not one of them.

Can I ask why you picked milliseconds that is not supported out of the box by the date & time functions in sqlite?

I'm curious how to deal when you need to call any of the date/time functions in the database (some operations already supported in ts-sql-query). The only solution that I can image is divide by 1000 before call the function, but you with the limitation you will lost the milliseconds each time you call those functions and you manipulate the date (right now not supported by ts-sql-query (but you can write it by yourself).

What you you think?, I can implement `Unix time milliseconds as integer` option with this limitation if you see as real general usage for other users.

**Comment by threema-danilo** [comment]
> I implemented all the options supported by [sqlite date and time functions](https://www.sqlite.org/lang_datefunc.html) and unix time in milliseconds is not one of them.

Ah, that makes sense!

> Can I ask why you picked milliseconds that is not supported out of the box by the date & time functions in sqlite?

Three reasons:

- It's the format we use in the network protocol of our application, so no transformations are needed
- We can pass it directly to the `Date` constructor in JS, and we can use `valueOf()` directly.
- Sometimes we want to retain proper sorting order even for events that happened in the same second (millisecond precision)

Right now I don't use any SQLite date functions and I'm unsure if I ever will. So that was not a concern.

> What you you think?, I can implement `Unix time milliseconds as integer` option with this limitation if you see as real general usage for other users.

I'm not sure, you're right about those limitations. Maybe this case should be handled with a custom type. On the other hand, losing milisecond precision when sending a `Date` to the database isn't ideal either.

**Comment by juanluispaz** [comment]
I'm going to implement `Unix time milliseconds as integer` for you, including the ability of every date and time function included in ts-sql-query to deal with the milliseconds representation. I will publish the changes late this night when I finish the implementation. I will appreciate if you give me your feedback when it is published.

**Comment by juanluispaz** [comment]
Version 1.17.0 published with support to `Unix time milliseconds as integer`
