### ISSUE TITLE
Question on inferring types for dynamic usage

### ISSUE THREAD

**Issue by lgrahl** [juanluispaz/ts-sql-query#29]
The strict typing is really great but it's very hard to infer what type one is looking at at a specific point during construction of the query. I'll explain it with a concrete example on why that caveat may be important.

### Example

Let's assume I have a long query and want to reuse a part of it. We have a table `tFoo` and in our case, the `.where` clause of a select should be conditional. 

So, I've determined that the type of `condition` in `where` is `IBooleanValueSource<TABLE_OR_VIEW[typeof tableOrViewRef] | NoTableOrViewRequired<DB>, boolean | null | undefined>`.

And I've also determined that I can use `mergeType`, in my case dumbing this down to "just" `BooleanValueSource<VALUE[typeof tableOrView], VALUE[typeof valueType]>`. I had no idea what that is but IIRC in my case it's essentially referring to the table and `boolean` which is what VSCode was able to infer when hovering over the resulting type.

So, I would have expected that I can just write:

```ts
function selectSomethingFromFoo(
  filter: BooleanValueSource<typeof tFoo, boolean>,
) {
  db.selectFrom(...).where(filter)
}
```

Because, after all, `tFoo` is my table where I select on. However, TS complains that

```
Type 'tFoo' does not satisfy the constraint 'TableOrViewRef<AnyDB>'.
  Property '[tableOrViewRefType]' is missing in type 'TMessage' but required in type 'TableOrViewRef<AnyDB>'
```

But how can that be? `tFoo` clearly extends `Table` which extends `TableOf` which does provide `[tableOrViewRef]: REF`.

### Questions

1. How to resolve this concrete scenario?
2. Is there a guide or a hint on how to infer a type so we can construct queries dynamically? Or can this be avoided somehow without having to repeat oneself?

**Comment by juanluispaz** [comment]
Hi!

Contrary what happens in JavaScript where the value of a property exists independently of the container, here a column reference cannot exists without the table that belong to; this situation make things complicated. In order to validate the queries each column have a type reference (and a real reference) to the value that belong to. The downside of this is you cannot create functions that allows reuse code easily. Said that, I provide several options to allows you get te maximum flexibility in your queries.

In your case looks like you want to define a common query that the only difference is the where, if you see [select clauses order](https://ts-sql-query.readthedocs.io/en/stable/queries/select/#select-clauses-order) you will notice you can differ the where till the end, that will allow you do something like:

```ts
function createSelectSomethingFromFoo(db: DBConection) { // I omit the return type to allow TS infer the type
    return db.selectFrom(tFoo).select({id: tFoo.Id, name: tFoo.name}) // even you can define some join, order by, etc.
}

function useTheQuery(db: DBConection, id: number): {id: number, name: string} {
    return createSelectSomethingFromFoo(db).where(tFoo.id.equals(id)).executeSelectOne()
}
```

Not sure why are you trying to do this; but, if you are trying to avoid repeat all select fields, you can do this:

```ts
const mySelectFields = {
   id: tFoo.id,
   name: tFoo.name
}

function useTheQuery(db: DBConection, id: number): {id: number, name: string} {
    return db.selectFrom(tFoo).select(mySelectFields).where(tFoo.id.equals(id)).executeSelectOne()
}
```

If the case is you want to include all fields of a table you can use the [extract columns](https://ts-sql-query.readthedocs.io/en/stable/advanced-usage/#extract-columns) function:

```ts
function useTheQuery(db: DBConection, id: number): {id: number, name: string} {
    return db.selectFrom(tFoo).select(extractColumnsFrom(tFoo)).where(tFoo.id.equals(id)).executeSelectOne()
}
```

I believe some of the previous options could work for you, if not, let me know with more information what are you trying to do.

Just in case, there are several options to deal with dynamic queries explained in the [dynamic queries](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/) section, with some options:

- The filter is a close list defined in your code, you can take advantage of the `*IfValue` functions (explained [here](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#easy-dynamic-queries) ) doing something like this:

Note: **The most probably is this is what you really need to do.**

```ts
function selectSomethingFromFoo(db: DBConection,
  filter: {id?: number, name?: string}
) {
  return db.selectFrom(tFoo)
        .select({id: tFoo.Id, name: tFoo.name})
        .where(tFoo.id.equalsIfValue(filter.id))
        .and(tFoo.name.containsInsensitiveIfValue(filter.name))
        .executeSelectOne()
}
```

In this case you define all the filters options in your query using the `*IfValue` functions, in this case if null, undefined or empty string is provided, that boolean expression will be omitted. In the previous example the code can work like the following functions:

```ts
function selectSomethingFromFoo1(db: DBConection,
  filter: {id: number}
) {
  return db.selectFrom(tFoo)
        .select({id: tFoo.Id, name: tFoo.name})
        .where(tFoo.id.equals(filter.id))
        .executeSelectOne()
}

function selectSomethingFromFoo2(db: DBConection,
  filter: {name: string}
) {
  return db.selectFrom(tFoo)
        .select({id: tFoo.Id, name: tFoo.name})
        .where(tFoo.name.containsInsensitive(filter.name))
        .executeSelectOne()
}

function selectSomethingFromFoo3(db: DBConection,
  filter: {id: number, name: string}
) {
  return db.selectFrom(tFoo)
        .select({id: tFoo.Id, name: tFoo.name})
        .where(tFoo.id.equals(filter.id))
        .and(tFoo.name.containsInsensitive(filter.name))
        .executeSelectOne()
}

function selectSomethingFromFoo4(db: DBConection,
  filter: {}
) {
  return db.selectFrom(tFoo)
        .select({id: tFoo.Id, name: tFoo.name})
        .executeSelectOne()
}
```

As you can see with the help of the `*IfValue` you can create a single function that behave differently depending if a value is present or absent. You only need you think how the query will looks like when all values are present and use `*IfValue` in the ones that can be optional.

- The filter is dynamically defined outside (like the UI or the REST service caller), in that case you can use [dynamic filters](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#select-using-a-dynamic-filter) that allows you to create a boolean condition from an object representation of the condition.

- Sometime you can find yourself repeating some piece of code that produces a value in several places, something that, if you do in the database you will use a sql function. In ts-sql-query you have the possibility to define [reusable fragment of code](https://ts-sql-query.readthedocs.io/en/stable/queries/sql-fragments/#select-with-custom-reusable-sql-fragment) that acts as a sql function (but resolved at the time you construct the query). This functionality allows you to create that reusable functions without deal with the internal ts-sql-query types. In the documentation example it is used to create a raw sql, but you can return any expression that return a ValueSource in ts-sql-query.

```ts
class DBConection extends PostgreSqlConnection<'DBConnection'> { 

    validateName = this.buildFragmentWithArgs(
        this.arg('string', 'required'),
        this.arg('string', 'required')
    ).as((value1, value2) => {
        return value1.containsInsensitive(value2)
    })
}

function selectSomethingFromFoo(db: DBConection, name: string) {
  return db.selectFrom(tFoo)
        .select({id: tFoo.Id, name: tFoo.name})
        .where(db.validateName(tFoo.name, name))
        .executeSelectOne()
}
```

Be aware, the internal type definitions (like `IBooleanValueSource`) are complex because several limitations:
- Values must track their origin.
- Values must track their different optionality rules: it is not the same an optional column that a column that looks as optional because it comes from a left join (by example).
- Values must track their projected type.
- Values must track their type in the database.
- Synthetic type definition are required to avoid TypeScript dead with complex types when it try to validate the query.

When you create a table, in your code `TMessage`, the class `TMessage` is for you the type of the table object, but, under the hood, a lightweight synthetic type is created with the name you provide when you do `Table<DBConection, 'TMessage'>`, that type extent `TableOrViewRef` you saw in the error. This double-type game happens everywhere in the library; if not, TypeScript will run so slowly. Because of all this complexities I don't expect you to deal with the internal types.

I beg you do not use the internal/private types of the library in your code, because they can change among versions. You can see the pubic types in the documentation [here](https://ts-sql-query.readthedocs.io/en/stable/#install)

Regarding `mergeType` (explained [here](https://ts-sql-query.readthedocs.io/en/stable/advanced-usage/#merge-types) ) I'm going to put a warning in the documentation to inform that it must be you last resource; first you can start using the `*IfValue` functions, if that is not enough you can use the complex dynamic boolean expressions (explained [here](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#complex-dynamic-boolean-expressions) ). The `mergeType` function must be the last resource.

Some explanations about the type shown by VSCode (I'm going to refer to the latest version that is different to the one you put in your comment)

If I have the following definition:

```ts
class DBConection extends SqliteConnection<'DBConnection'> {
}

const tCompany = new class TCompany extends Table<DBConection, 'TCompany'> {
    id = this.autogeneratedPrimaryKey('id', 'int');
    name = this.column('name', 'string');
    constructor() {
        super('company'); // table name in the database
    }
}()
```

Pay attention to the string you passed as generic argument in the connection and table object, that string will be used to define the identity of that object.

The type of `tCompany.id` is:

```ts
NumberValueSource<TABLE<DB<"DBConnection">, "TCompany">, "required"> & ColumnWithDefaultValue & PrimaryKeyColumn & PrimaryKeyAutogeneratedColumn
```

There is the type of the column: 

```ts
NumberValueSource<TABLE<DB<"DBConnection">, "TCompany">, "required">
```

That means, this value source represents a number (`NumberValueSource`), coming from a database with name "DBConnection" (`DB<"DBConnection">`, that is the DBConection class); this value source requires the "TCompany" table  (`TABLE<..., "TCompany">`, here can be several tables joined using | the or in TS); the optional rule is "required", that means this values is always required, in consequence, it never contains null.

Additionally there is the following marks:
- `ColumnWithDefaultValue`: This means this value represents a column (it is not a computed value) that contains a default value (in consequence it can be omitted when insert)
- `PrimaryKeyColumn`: This means this value represents the primary key column; the value of this column is the value returned when you insert returning the last inserted id
- `PrimaryKeyAutogeneratedColumn`: This means this value represents the primary key column that is generated automatically in the database (in consequence it can be omitted when insert)

If I do the following expression `tCompany.id.equals(1234)` the type will be:

```ts
BooleanValueSource<TABLE<DB<"DBConnection">, "TCompany">, "required">
```

The logic is the same, the difference is there is no marks of column (because this value doesn't represent a column any more) and the type is a boolean

If I do the following expression `tCompany.id.equalsIfValue(1234)` the type will be:

```ts
IfValueSource<TABLE<DB<"DBConnection">, "TCompany">, "required">
```

`IfValueSource` means this is a boolean expression that can contains no value, and in the case there is no value, it will be omitted from the further boolean expression.

Be aware `BooleanValueSource` and `NumberValueSource` are the full type, but, there exists another variant that starts with `I` that is a lightweight version of that type, that is `IBooleanValueSource` and `INumberValueSource` that represents the same, but reduces the pressure over the type validation in TS. As general rule, when the library produces a value source it will be the version without `I`, but, when the library expect a value source (like as argument of a function) the version with `I` will be used.


Additionally there is a invisible auxiliar table called `NoTableOrViewRequired` that allows represents constant values/expressions that doesn't required any table or view to produce a value. As example, if you call `db.currentDateTime()` the type will be: 

```ts
DateTimeValueSource<NoTableOrViewRequired<DB<"DBConnection">>, "required">
```

That means, this is a date-time value that is usable in the database "DBConnection", but it doesn't requires any table or view.

Please, let me know if I answered your question; or give me more information about what are you trying to do (think in what, not in how) and I happily will answer you. Think, maybe you found something that I need to considere for future versions.

**Comment by lgrahl** [comment]
Many thanks for this elaborate answer! It goes way beyond the specific use case I had and I can't say I have grasped everything in your response but since I (intentionally) asked this very general question, this was to be expected and perhaps it helps others when encountering similar issues. :slightly_smiling_face: 

You make a good point on inferring the return type by simply not explicitly specifying a return type for the function. We have a linting rule that disallows that for functions in general (for various reasons, one being that explicit return types are a form of documentation and one being that the project is large and inferring can take time) but I think its perfectly fine to make an exception for such helper functions.

**Comment by juanluispaz** [comment]
I added a note to the [merge types function documentation](https://ts-sql-query.readthedocs.io/en/latest/advanced-usage/#merge-types) redirecting the reader to the different alternatives
