### ISSUE TITLE
Impossible to create an empty where condition

### ISSUE THREAD

**Issue by Dominik-Reinert** [juanluispaz/ts-sql-query#4]
Right now, when trying to select something with a query, there is no way to not have a 'where()' clause.

`select * from <table>` 

A workaround however is currently:

```
Table<MyDb> {
  id = this.autogeneratedPrimaryKey("id", "int");
  constructor() {
    super("my_table");
  }
}

connection.selectFrom(myTable).where(myTable.id.isNotNull())
```

**Comment by juanluispaz** [comment]
You can do this:

```ts
const customerWithId = connection.selectFrom(tCustomer)
    .select({
        id: tCustomer.id,
        firstName: tCustomer.firstName,
        lastName: tCustomer.lastName,
        birthday: tCustomer.birthday
    })
    .executeSelectMany()
```

And the next sql query (with an empty list of params) will be executed:

```sql
select id as id, first_name as firstName, last_name as lastName, birthday as birthday 
from customer
```

`select *` is intentionally disallowed because it is a bad practice when you are building system (but really useful when you are querying the database directly); you must always specify what columns you want to get from the database.
