### ISSUE TITLE
field after dynamicPick

### ISSUE THREAD

**Issue by mkupriichuk** [juanluispaz/ts-sql-query#50]
Hello
We have the next dynamicPick

```ts
const optionalFieldsToPick = {
    productAmount: metricField === 'productAmount',
    productCount: metricField === 'productCount'
};

const periodSelect = {
    productId: agOrderTable.saProductId,
    productAmount: connection.sum(agOrderTable.productAmount),
    productCount: connection.sum(agOrderTable.productCount)
};

const periodDynamicSelect = dynamicPick(periodSelect, optionalFieldsToPick, ['productId'])

// use in query

const allPeriodQuery = connection
      .selectFrom(agOrderTable)
      .optionalInnerJoin(saProductCategoryTable)
      .on(saProductCategoryTable.saProductId.equals(agOrderTable.saProductId))
      .where(agOrderTable.date.greaterOrEquals(previousPeriod.from).and(agOrderTable.date.lessOrEquals(currentPeriod.to)))
      .select(periodDynamicSelect)
      .groupBy('productId')
      .forUseInQueryAs('allPeriodQuery');

const currentPeriodQuery= connection
      .selectFrom(agOrderTable)
      .where(agOrderTable.date.greaterOrEquals(currentPeriod.from).and(agOrderTable.date.lessOrEquals(currentPeriod.to)))
      .select(periodDynamicSelect)
      .groupBy('productId')
      .forUseInQueryAs('currentPeriodQuery')
      .forUseInLeftJoin();
```

Next, we need to make a main query with another ```dynamicPick```, in which calculations will be made from the results above

```ts
// Second dynamic select

const mainQuerySelect = {
      productId: allPeriodQuery.productId,
      productAmount: currentPeriodQuery.productAmount
        .valueWhenNull(0)
        .multiply(2)
        .substract(allPeriodQuery.productAmount.valueWhenNull(0)),
      productCount: currentPeriodQuery.productCount
        .valueWhenNull(0)
        .multiply(2)
        .substract(allPeriodQuery.productCount.valueWhenNull(0)),
};

const mainQueryDynamiSelect = dynamicPick(mainQuerySelect, optionalFieldsToPick, ['productId'])

return await connection
      .selectFrom(allPeriodQuery)
      .leftJoin(currentPeriodQuery)
      .on(currentPeriodQuery.productId.equals(allPeriodQuery.productId))
      .select(mainQueryDynamiSelect)
      .executeSelectMany()
```

And we got a error on  ```mainQuerySelect```: ```Cannot read properties of undefined (reading 'valueWhenNull')```
Although we should have one of the two fields anyway - ```productAmount``` or ```productCount```

Maybe we are doing something wrong?

**Comment by juanluispaz** [comment]
Hi,

When a column is not picket, that column doesn't exists in the final query at all; therefore, you cannot reference to them in a further query. It is not that column will be null, it is that column doesn't exists.

I cannot imagine an inner query with a picking columns, because now the query columns are not stable, they maybe doesn't exists. I only expect to see the picking columns in the final outer query; allowing the database optimise the query. Or if you prefer, you control the generated sql.

In your case you have two options:

- **Allow the database optimise the query**: You can remove the picking in the inner query and preserve the picking in the external query, this is the easiest one

- **Control by yourself the generated query**: You can build a custom sql fragment that apply the logic you want, for this you can add this fragment to your connection class:

```ts
    ignoreWhen = this.buildFragmentWithArgs(
        this.valueArg('boolean', 'required'),
        this.arg('int', 'optional')
    ).as((condition, value) => {
        if (condition.getConstValue()) {
            return value
        } else {
            return this.fragmentWithType('int', 'optional').sql`null::int`
        }
    })
```

Then in your query you can do:

```ts
productAmount: connection. ignoreWhen(metricField === 'productAmount', connection.sum(agOrderTable.productAmount)),
```

Don't forget remove the picking in the inner query.

What this do is always create the columns in the inner column, but put null when it is not required.

Please, let me know if this is what your had in mind

**Comment by juanluispaz** [comment]
Hi

I implemented the function that transform the expression in null according to a condition in ts-sql-query 1.46.0. You can see the details here: https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#ignorable-expression-as-null
