### ISSUE TITLE
Will ts-sql-query support dialect specific operations like `for update`?

### ISSUE THREAD

**Issue by xialvjun** [juanluispaz/ts-sql-query#6]
just the title

**Comment by juanluispaz** [comment]
There are already some features implemented only for some databases, like:
- Insert multiple rows returning las inserted id (Supported by PostgreSql, SqlServer, and Oracle)
- Insert from select returning las inserted id (Supported by PostgreSql and SqlServer)

Then, the answer to your question is yes!!!

I only request you some explanations to understand your use case.

For the case "for update", you usually don't want to do it on your backend because of the delay in the communications between the server and the database (remember, during this time, the row is locked). The common approach and best practice are implementing the "for update" logic inside a stored procedure to reduce the lock to a minimum.

Let me know if you miss some feature, even when it can be dialect-specific, and I will do my best to implement it.
