### ISSUE TITLE
Select exists

### ISSUE THREAD

**Issue by lithdew** [juanluispaz/ts-sql-query#64]
Hi,

A question: how would I be able to model the following query with this library?

```sql
select
    (select exists(select * from follows f join follows aa on aa.public_key = $1 where f.follower_id = aa.id and f.following_id = accounts.id)) as follower
from accounts
```

My struggle is trying to model the inlined query `select exists(...)`. Here is my attempt:

```ts
type Storage = "r2";

const accounts = new class Accounts extends Table<DBConnection, 'Accounts'> {
    id = this.primaryKey("id", "string");
    publicKey = this.column("public_key", "string");
    name = this.column("name", "string");
    alias = this.optionalColumn("alias", "string");
    bio = this.column("bio", "string");
    avatarStorageId = this.optionalColumn<Storage>("avatar_storage_id", "enum", "Storage");
    avatarEtag = this.optionalColumn("avatar_etag", "string");
    createdAt = this.column("created_at", "localTime");
    updatedAt = this.column("updated_at", "localTime");
    lastSeenAt = this.column("last_seen_at", "localTime");
    isVerified = this.column("is_verified", "boolean");

    constructor() {
        super("accounts");
    }
}

const follows = new class Follows extends Table<DBConnection, "Follows"> {
    followerId = this.column("follower_id", "string");
    followingId = this.column("following_id", "string");
    createdAt = this.column("created_at", "localTime");

    constructor() {
        super("follows");
    }
}

const sessionPublicKey: string | null = null;

const user = accounts.as("aa");

// ... errors on 'connection.exists(...)' being passed to 'selectFromNoTable().selectOneColumn(...)'.
const followed = connection.selectFromNoTable().selectOneColumn(
    connection.exists(
        connection
            .subSelectUsing(accounts)
            .from(follows)
            .optionalJoin(user).on(user.publicKey.equalsIfValue(sessionPublicKey))
            .where(follows.followerId.equals(accounts.id))
            .and(follows.followingId.equals(user.id))
            .selectOneColumn(connection.countAll()),
    )
);

const results = await connection
    .selectFrom(accounts)
    .select({
        followed: followed.forUseAsInlineQueryValue(),
    })
    .executeSelectMany();
```

**Comment by juanluispaz** [comment]
You have several queries here, each one depending of an external table, the innermost query have the `subSelectusing`, that is wrapped in another query, that query will required indicate that query depends on external table, I have no `selectFromNoTable` that allow indicate the external table, and that makes no sense at all.

I suggest rewrite your query as (with one select less that aport no value) :

```sql
select
    exists(select f.follower_id from follows f join follows aa on aa.public_key = $1 where f.follower_id = aa.id and f.following_id = accounts.id) as follower
from accounts
```

then, it will be like:

```ts
const followed = connection.exists(
        connection
            .subSelectUsing(accounts)
            .from(follows)
            .join(user).on(user.publicKey.equalsIfValue(sessionPublicKey)) // You don't need to use optionalJoin here
            .where(follows.followerId.equals(accounts.id))
            .and(follows.followingId.equals(user.id))
            .selectOneColumn(follows.followerId),
    );

const results = await connection
    .selectFrom(accounts)
    .select({
        followed: followed,
    })
    .executeSelectMany();
```

Note: I replaced * by `follows.followerId`

Or even better (this query perform better):

```ts
const followed = connection
            .subSelectUsing(accounts)
            .from(follows)
            .join(user).on(user.publicKey.equalsIfValue(sessionPublicKey)) // You don't need to use optionalJoin here
            .where(follows.followerId.equals(accounts.id))
            .and(follows.followingId.equals(user.id))
            .selectOneColumn(connection.countAll())
            .valueWhenNull(0)
            .greaterOrEquals(0)
    );

const results = await connection
    .selectFrom(accounts)
    .select({
        followed: followed,
    })
    .executeSelectMany();
```

Note: I use here `connection.countAll()`

Important, you are using `optionalJoin` where there is no way that join will not be used, you can use a regular join. `optionalJoin` indicate to the library that join can be removed from the final query if it is not used (maybe because you are using a [Select dynamically picking columns](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#select-dynamically-picking-columns) or [Select using a dynamic filter](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#select-using-a-dynamic-filter)); if you don't use this you can use regular joins (if you use `optionalJoin` it will have no consequences in the final query because the join is always used in the query)

Be aware, [Select dynamically picking columns](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#select-dynamically-picking-columns), [Select using a dynamic filter](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#select-using-a-dynamic-filter) and [Optional joins](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#optional-joins) are the most extreme expression of dynamic queries, several times people ask me about it, but in rare cases they really need it, most of the time they are looking for other things. 

You need [Select dynamically picking columns](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#select-dynamically-picking-columns) features when the returned columns can change according the request (by example, the UI said only few columns are required. The [Select using a dynamic filter](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#select-using-a-dynamic-filter) feature is required when the UI send a structure saying the conditions for the where, you don't need this if you need dynamic queries that are defined in the back (there are other options, especially the [*IfValue](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#easy-dynamic-queries) functions). The [Optional joins](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#optional-joins) feature help to deal with joins when you use the [Select using a dynamic filter](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#select-using-a-dynamic-filter) or [Select dynamically picking columns](https://ts-sql-query.readthedocs.io/en/stable/queries/dynamic-queries/#select-dynamically-picking-columns), if not, it add no value, but complexity for you understand the query.

**Comment by lithdew** [comment]
I tried out the former code with the `select` wrapping around the `exists(...)` subquery removed and noticed that the `join(user).on(...)` clause got removed from the resulting query.

```ts
const sessionPublicKey: string | null = null;

const user = accounts.as("user");

const results = await connection
    .selectFrom(accounts)
    .select({
        followed: connection.exists(
            connection
                .subSelectUsing(accounts)
                .from(follows)
                .join(user).on(user.publicKey.equalsIfValue(sessionPublicKey))
                .where(follows.followerId.equals(accounts.id))
                .and(follows.followingId.equals(user.id))
                .selectOneColumn(follows.followerId),
        ),
    })
    .executeSelectMany();
```

Resulting query:
```sql
SELECT exists
  (SELECT follows.follower_id AS RESULT
   FROM follows
   JOIN accounts AS "user"
   WHERE follows.follower_id = accounts.id
     AND follows.following_id = "user".id) AS followed
FROM accounts
```

It appears, as you mentioned, that the problem comes from my error of using `equalsIfValue`. As I am looking to dynamically pick values for a project I'm working on, I should not have used optionalJoin/equalsIfValue and should instead dynamically have the follower field picked.

Thank you once again for the help.

**Comment by juanluispaz** [comment]
Good!!

Let me point some things

We use a lot the `*IfValue` functions, they are very useful to write dynamic query (understand it as the generated sql changes)

An `myColumn.equalsIfValue(myOptionalValue)` is similar to write in your code:

```ts
let myStringSql = '.... sql '
let params = [... with values required before]

if (myOptionalValue) {
    params.push(myOpyionalValue)
    myStringSql =+ `and myColumn = %%{params.lenght}`  // I use and here as example, in ts-sql-query the proper and/or will be generated or omitted if that is not required
}
```

As you see the query changes, the final string is not the same; and the comparison is not performed when no value

In your case there is something that caught my attention:

```ts
const sessionPublicKey: string | null = null;
```

It is like it should not be nullable in a regular basis; but, in case it should be nullable, the question is how the subquery must behave, I think it should return false. In SQL the equals operator between two nulls is a false value, but few developers known about this and it is very unusually used. What you really what is use that behaviour.

Due `user.publicKey` the regular equals function will not allow to provide a nullable value, but you can transform `user.publicKey` in optional, and then archive the described behaviour. 

```ts
const results = await connection
    .selectFrom(accounts)
    .select({
        followed: connection.exists(
            connection
                .subSelectUsing(accounts)
                .from(follows)
                .join(user).on(user.publicKey.asOptional().equals(sessionPublicKey))
                .where(follows.followerId.equals(accounts.id))
                .and(follows.followingId.equals(user.id))
                .selectOneColumn(follows.followerId),
        ),
    })
    .executeSelectMany();
```

The `asOptional()` function no affects the generated SQL, but instead allows TypeScript and the inner processing of the result that value can be null, let me show you, `user.publicKey.equals(sessionPublicKey)` the result type in SQL is `boolean`,  but, `user.publicKey.asOptional().equals(sessionPublicKey)` the result type in SQL is `boolean | null`, been null a falsy value.

But I must insist, it sound like `sessionPublicKey` it should not be null in a general usage.

**Comment by juanluispaz** [comment]
Sorry for the error answering you.

The issue with `a = b` when null is involved is Sql uses ternary logic instead of regular Boolean logic, that creates a lot of unexpected behaviour in the query if you are not aware of this; In our internal use it creates so many misunderstanding and issues that I deprecated that behaviour, as well it created more issues if we want to introspect the query.

Then if you want to have that behaviour you have two options:

```ts
user.publicKey.equalsIfValue(sessionPublicKey).falseWhenNoValue()
```

Then your query will looks like:

```ts
const results = await connection
    .selectFrom(accounts)
    .select({
        followed: connection.exists(
            connection
                .subSelectUsing(accounts)
                .from(follows)
                .join(user).on(user.publicKey.equalsIfValue(sessionPublicKey).falseWhenNoValue())
                .where(follows.followerId.equals(accounts.id))
                .and(follows.followingId.equals(user.id))
                .selectOneColumn(follows.followerId),
        ),
    })
    .executeSelectMany();
```

or you can define your custom sql fragment that do it:

```ts
class DBConnection extends PostgreSqlConnection<'DBConnection'> { 

    equalsFalsyOptionalString = this.buildFragmentWithArgs(
        this.arg('string', 'optional'),
        this.arg('string', 'optional')
    ).as((left, right) => {
        // The fragment here is: ${left} = ${right}
        return this.fragmentWithType('boolean', 'optional').sql`${left} = ${right}`
    })
}
```

Then your query will looks like:

```ts
const results = await connection
    .selectFrom(accounts)
    .select({
        followed: connection.exists(
            connection
                .subSelectUsing(accounts)
                .from(follows)
                .join(user).on(connection.equalsFalsyOptionalString(user.publicKey, sessionPublicKey))
                .where(follows.followerId.equals(accounts.id))
                .and(follows.followingId.equals(user.id))
                .selectOneColumn(follows.followerId),
        ),
    })
    .executeSelectMany();
```
