### ISSUE TITLE
Using the json data type

### ISSUE THREAD

**Issue by ibox4real** [juanluispaz/ts-sql-query#76]
Hello! Let me first thank you for this awesome project. I have been looking to move away from complex orm's for years, but none of the sql query builders i saw were as flexible and feature rich as this.

I looked at the data types and i saw that json datatype is not supported for any database. I figured the type adapter can be used for saving/retrieving from json column.

Lets say there is a json column `rgb` with three properties red,green,blue; 

```
type RGB {
   red: number,
   green: number,
   blue: numer,
}
``` 

What startegy would you suggest for selecting, filtering, ordering data based on those properties?  

```
//mysql syntax
SELECT rgb FROM colors WHERE rgb->'$.green' > 200 ORDER BY rgb->'$.green' ASC
```

**Comment by juanluispaz** [comment]
Hello!

Thanks; that is why I started this project years ago; I wanted to have a type-safe query builder for real day-to-day usage in complex situations, including lof of my experiences in the past.

ts-sql-query doesn't include a generic JSON type by default because you will want to define the proper type for that JSON. If you use a database that already supports JSON (like PostgreSQL), you only need to map it using a [custom](https://ts-sql-query.readthedocs.io/en/stable/column-types/) type. Still, suppose your database doesn't support it (like Sqlite). In that case, you will want to store the JSON as text in your database; then, you will need, additionally, to use an adapter to transform the object to a JSON string when it is sent to the database and to rehydrate the object when it is returned from the database.

ts-sql-query offers you ways to deal with situations where you need to use features not yet supported by the library. In your case, you want to access a property inside the JSON object, this feature is not included in the current version of ts-sql-query, but you can create your [own function with a SQL fragment](https://ts-sql-query.readthedocs.io/en/stable/queries/sql-fragments/#select-with-custom-reusable-sql-fragment) and use it in your code in a safe way. I expect the ts-sql-query in some moment need to use [SQL fragments](https://ts-sql-query.readthedocs.io/en/stable/queries/sql-fragments/). With this strategy, you can extract a value from a property in a JSON object to be returned by your select or used in a condition.

Regarding the order by, right now there is a [limitation that only allow specifying an order by over returned fields](https://ts-sql-query.readthedocs.io/en/stable/faqs-limimitations/#how-to-order-a-query-by-a-column-not-returned-by-the-select); but, you can provide your own SQL fragment for the order by and encircle it. Be aware your SQL fragment can receive ts-sql-query's object; in that way, you don't need to write everything in plain text dealing with naming, etc.

Let me know if I understandably expressed myself, and don't doubt to contact me if you have questions or any requirements you want to be included in the library; I will be pleased to help you.
