### ISSUE TITLE
Type narrowing from where clause when null has been checked

### ISSUE THREAD

**Issue by muniter** [juanluispaz/ts-sql-query#78]
Can optional columns be narrowed to non optional when checked for nullability in the where clause?

```typescript
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../connection-source";
import { CONNECTION as connection } from "../connection-source";

export class SuscritoTable extends Table<DBConnection, 'SuscritoTable'> {
    id = this.primaryKey('id', 'int');
    estrato = this.optionalColumn('estrato', 'int');

    constructor() {
        super('suscrito')
    }
}

export const tSuscrito = new SuscritoTable();

const result = connection.selectFrom(tSuscrito).where(
  tSuscrito.estrato.isNotNull()
).select({
  id: tSuscrito.id,
  estrato: tSuscrito.estrato,
}).executeSelectMany();
```

Result infers the following type:

```typescript
const result: Promise<{
    id: number;
    estrato?: number | undefined;
}[]>
```

I was hoping it could narrow / infer estrato type to be non optional, like:

```typescript
const result: Promise<{
    id: number;
    estrato: number;
}[]>
```

Thanks for this great library!

**Comment by juanluispaz** [comment]
Hi,

That will be great, unfortunately TypeScript doesn't offer a way to do it :( or other possibilities are too heavy to be a valid solution.

As workaround you have two options:

1. You add a fallback value in case of null (that never will happen) using the function `valueWhenNull`
2. You add you own unsafe function that transform an optional values in a required value without any fallback using a [custom reusable sql fragment](https://ts-sql-query.readthedocs.io/en/stable/queries/sql-fragments/#select-with-custom-reusable-sql-fragment) like this:

```ts
class DBConnection extends PostgreSqlConnection<'DBConnection'> { 

    intAsRequired = this.buildFragmentWithArgs(
        this.arg('int', 'optional'),
    ).as((value) => {
        return this.fragmentWithType('int', 'required').sql`${value}`
    })
}
```

and then use it in your query as:

```ts
const result = connection.selectFrom(tSuscrito).where(
  tSuscrito.estrato.isNotNull()
).select({
  id: tSuscrito.id,
  estrato: connection.intAsRequired(tSuscrito.estrato),
}).executeSelectMany();
```

Be aware, in case the query return a null value in `tSuscrito.estrato` the library will throw an error telling you an unexpected null value was found.

Note: I didn't include this kind of function by default because it can dangerous if you doesn't now what are you doing.

**Comment by muniter** [comment]
Thank you very much for the answer. I really like the idea of extending with SQL fragment. What I'm doing right now is running into through zod after and throwing and error if the field comes back undefined, and therefore having the expected return type.
