### ISSUE TITLE
column with decimal type

### ISSUE THREAD

**Issue by mkupriichuk** [juanluispaz/ts-sql-query#94]
Hello
Wee need to set column with ```decimal(27,8)``` type.
I try this:
```
frequencyDiff = this.column('frequencyDiff', 'custom', 'decimal');
```

But then i get error, when try to call ```greatestOnEqual``` on value:
```
Property 'greaterOrEquals' does not exist on type 'EqualableValueSource<VIEW<DB<"Connection">, "BasketAnalysisProductProductTable">, unknown, "decimal", "required"> & Column'.
```

We need to put some generic into  this.column<?> ?
Is there a correct way to do this? Thanks.

**Comment by juanluispaz** [comment]
Hi!

When you define the column type in ts-sql-query, it asks about the projected type, not the type in the database.

In your database, you have `decimal(27, 8)`; the question is what type you want to use in JS/TS; you can map as `double`, which will use `number` in JS/TS, but, you risk to loose precision depending on the number of digits in your decimal (most of the cases 15 digits of precision is mostly safe, that means, counting integer and decimal parts), or you can use `stringDouble` that will use `number | string` without loose precision.

Usually, when I design a database, I try to use native processor types (when possible) to avoid issues moving data across systems; that means, in PostgreSQL, I usually use:

- `smallint ` or `smallserial ` (2 bytes int) that can be represented in most languages as `short`; in JS you can represent with `number` or `bigint`, but they don't have the same precision because they can contain bigger numbers
- `integer` or `serial` (4 bytes int) that can be represented in most languages as `int`; in JS you can represent with `number` or `bigint`, but they don't have the same precision because they can contain bigger numbers
- `bigint` or `bigserial` (8 bytes int) that can be represented in most languages as `long`, in JS you can represent with `bigint`, but it doesn't have the same precision because it can contain bigger numbers
- `real`(4 bytes floating point) that can be represented in most languages as `float`; in JS you can represent with `number`, but it doesn't have the same precision because it can contain more precise numbers
- `double precision` (8 bytes floating point) that can be represented in most languages as `double`; in JS you can represent with `number`, and that will be an exact representation because that is what a number is in JS

When you get out of the numeric types supported by the processor, you must be careful because it is easy to mess up, especially if you process those numbers out of the database; in Java you have the `BigDecimal` class to help you deal with these numbers; but any basic math operation get more complicated because you will need to think in the math operation and in the precision (and rounding) of that resulting operation. 

An important question here will be what database and connector you are using because, depending on how it deals with the data, you can find issues.

In pg (for PostgreSQL), for this type, it will return a string when there is a risk of loose precision. That is why it exists `stringDouble` in ts-sql-query.

In the last years, they added `bigint to deal with the integer cases in JS, but there is no equivalent to bignumber / bigdecimal; in consequence, it is common SQL connectors to return those values as string.

I was thinking of adding support to [decimal.js](https://mikemcl.github.io/decimal.js/) to allow you to project that values as that type; doing under-the-hood the string or number transformation to this type, but till nowadays, no one requires it, even in our internal projects; usually with the string representation had been enough.

Regarding the custom column type, it expects the generic type, as well as it will not expose the math functions to use in your queries, just the safe ones for that kind of column; you can bypass using sql-fragments.

The question here is how you want to project that value in TS/JS; let me know what you have in mind and what you need; I have a special interest in this topic to know how to move forward with the library regarding decimal numbers.

[Column type documentation](https://ts-sql-query.readthedocs.io/en/stable/column-types/)

**Comment by mkupriichuk** [comment]
Thank you for such a comprehensive response. We decided to keep the type ```double```
